name: first_webapp
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: cfau214 <c.fauteux@my.ccsu.edu>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
  pedantic: ^1.0.0
